server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: song-services
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/songs/**
          filters:
            - RewritePath=/songs/(?<segment>.*), /$\{segment}

        - id: user-services
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}



eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
  instance:
    hostname: localhost
